version: '3'
services:
  db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
    networks:
      - OptiMemo_docker_network
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    depends_on:
      - db
    command: rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    volumes:
      - .:/OptiMemo
    networks:
      - OptiMemo_docker_network
    ports:
      - "3000:3000"
    env_file:
      - .env
    container_name: OptiMemo_web_container

volumes:
  db_data:

networks:
  OptiMemo_docker_network:
    name: OptiMemo_docker_network